version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/maat-court-data-api"
    schedule:
      interval: "daily"
    target_branch: "master"
    commit-message:
      prefix: "Gradle"
      include: "scope"
