{{- if .Values.ingress.enabled -}}
{{- $fullName := include "laa-maat-data-api.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-external
  labels:
    {{- include "laa-maat-data-api.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- include "laa-maat-data-api.externalIngress" . | nindent 2 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.externalHost }}
    - host: {{ $.Values.ingress.externalHost.host | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.externalHost.paths.swaggerPath }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          - path: {{ $.Values.ingress.externalHost.paths.openApiPath }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          - path: {{ $.Values.actuator.health.path }}
            pathType: "Exact"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.actuator.port }}
    {{- end }}
  {{- end }}
