name: Slack channel notification
description: "Send notification to Slack channel"

inputs:
  webhook-url:
    description: "The webhook URL of the Slack channel."
    required: true
  job-status:
    description: "The status of the calling job."
    required: true

runs:
  using: "composite"
  steps:
    - name: Calculate deployment time
      id: deployment-time
      shell: bash
      run: |
        echo "DEPLOYMENT_TIME=$(date +'%d/%m/%Y %T')" >> $GITHUB_OUTPUT

    - name: Notify success to Slack
      id: slack-success
      if: ${{ inputs.job-status == 'success' }}
      uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c #v3
      with:
        webhook: ${{ inputs.webhook-url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Deployment Successful! :partying_face:",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  { "type": "mrkdwn", "text": "*Project:* ${{ github.event.repository.name }}" },
                  { "type": "mrkdwn", "text": "*When:* ${{ steps.deployment-time.outputs.DEPLOYMENT_TIME }}" },
                  { "type": "mrkdwn", "text": "*Branch:* \n${{ github.ref_name }}" },
                  { "type": "mrkdwn", "text": "*Successful Job:* \n${{ github.job }}" }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "action_id": "deployment_link",
                    "text": { "type": "plain_text", "text": "View Run" },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }

    - name: Notify failure to Slack
      if: ${{ inputs.job-status != 'success' }}
      uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c
      with:
        webhook: ${{ inputs.webhook-url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Deployment Failed :x:",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  { "type": "mrkdwn", "text": "*Repo:* ${{ github.repository }}" },
                  { "type": "mrkdwn", "text": "*Branch:*\n${{ github.ref_name }}" },
                  { "type": "mrkdwn", "text": "*Job:*\n${{ github.job }}" },
                  { "type": "mrkdwn", "text": "*Actor:*\n${{ github.actor }}" },
                  { "type": "mrkdwn", "text": "*When:* ${{ steps.deployment-time.outputs.DEPLOYMENT_TIME }}" },
                  { "type": "mrkdwn", "text": "*Workflow:*\n${{ github.workflow }}" }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "action_id": "run_link",
                    "text": { "type": "plain_text", "text": "View Run" },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }