CREATE SCHEMA IF NOT EXISTS MLA;
CREATE SCHEMA IF NOT EXISTS TOGDATA;
CREATE SEQUENCE  IF NOT EXISTS "MLA"."TXID";
CREATE SEQUENCE  IF NOT EXISTS "MLA"."CASEID";
CREATE SEQUENCE  IF NOT EXISTS "MLA"."PROCEDING";
CREATE SEQUENCE  IF NOT EXISTS "MLA"."LIBRAID";
