version: "3.5"

services:
  app:
    build:
      context: .
    environment:
      - SENTRY_ENV=development
      - CLOUDWATCH_STEP=1m
      - CLOUDWATCH_BATCH_SIZE=20
      - ENABLE_CLOUDWATCH_METRICS=false
      - ENABLE_SPRING_CLOUD_SQS=false
      - POST_MVP_ENABLED=false
      - LOG_LEVEL=INFO
      - JWT_ISSUER_URI=https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_zAlvz7NlW
    env_file:
      - app.env

    networks:
      local-container-network:
        aliases:
          - court-data-api
          - maat-court-data-api

    ports:
      - "8090:8090"
      - "8091:8091"
      - "8100:8100"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8091 -jar app.jar

networks:
  local-container-network:
    driver: bridge
    name: local-container-network
