ALTER TABLE TOGDATA.CONTRIBUTION_FILE_ERRORS DROP COLUMN CREATION_DATE;
ALTER TABLE TOGDATA.CONTRIBUTION_FILE_ERRORS DROP COLUMN FDC_CONTRIB_ID;
ALTER TABLE TOGDATA.CONTRIBUTION_FILE_ERRORS DROP COLUMN CONCOR_CONTRIB_ID;