ALTER TABLE "TOGDATA"."REP_ORDER_COMMON_PLATFORM_DATA" ADD IN_COMMON_PLATFORM VARCHAR2(3);

ALTER TABLE "TOGDATA"."REP_ORDER_COMMON_PLATFORM_DATA" MODIFY DATE_CREATED TIMESTAMP(6);

UPDATE togdata.REP_ORDER_COMMON_PLATFORM_DATA SET IN_COMMON_PLATFORM='Y' WHERE DEFENDANT_ID is not null;

commit;