CREATE INDEX "TOGDATA"."REP_ORDER_SENT_ORD_DATE_IDX" ON "TOGDATA"."REP_ORDERS" ("ID", "SENTENCE_ORDER_DATE");
CREATE INDEX "TOGDATA"."CONTRIBUTIONS_REP_STATUS_IDX" ON "TOGDATA"."CONTRIBUTIONS" ("REP_ID", "TRANSFER_STATUS");
CREATE INDEX "TOGDATA"."CONCOR_CONTRIBUTIONS_REP_STATUS_IDX" ON "TOGDATA"."CONCOR_CONTRIBUTIONS" ("REP_ID", "STATUS");
CREATE INDEX "TOGDATA"."FDC_ITEMS_FDC_ID_IDX" ON "TOGDATA"."FDC_ITEMS" ("FDC_ID");
CREATE INDEX "TOGDATA"."FDC_CONT_LGFS_AGFS_IDX" ON "TOGDATA"."FDC_CONTRIBUTIONS" ("LGFS_COMPLETE", "AGFS_COMPLETE");