DROP INDEX "TOGDATA"."REP_ORDER_SENT_ORD_DATE_IDX";
DROP INDEX "TOGDATA"."CONTRIBUTIONS_REP_STATUS_IDX";
DROP INDEX "TOGDATA"."CONCOR_CONTRIBUTIONS_REP_STATUS_IDX";
DROP INDEX "TOGDATA"."FDC_ITEMS_FDC_ID_IDX";
DROP INDEX "TOGDATA"."FDC_CONT_LGFS_AGFS_IDX";
