ALTER TABLE TOGDATA.CONTRIBUTION_FILE_ERRORS ADD CREATION_DATE TIMESTAMP(6);
ALTER TABLE TOGDATA.CONTRIBUTION_FILE_ERRORS ADD FDC_CONTRIB_ID NUMBER;
ALTER TABLE TOGDATA.CONTRIBUTION_FILE_ERRORS ADD CONCOR_CONTRIB_ID NUMBER;