DROP TABLE MLA.XXMLA_WQ_PLEA CASCADE CONSTRAINTS;

CREATE TABLE MLA.XXMLA_WQ_PLEA
(
--     TRANSACTION_UUID VARCHAR2(200 BYTE) NOT NULL,

    PLEA_ID NUMBER NOT NULL,
    PLEA_VALUE VARCHAR2(100 BYTE),
    PLEA_DATE DATE,
    OFFENCE_ID VARCHAR2(50),
    CREATED_ON TIMESTAMP (6) NOT NULL,
    CREATED_BY VARCHAR2(50)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;



DROP TABLE MLA.XXMLA_WQ_VERDICT CASCADE CONSTRAINTS;

CREATE TABLE MLA.XXMLA_WQ_VERDICT
(
    VERDICT_ID NUMBER NOT NULL,
    OFFENCE_ID VARCHAR2(50),
    VERDICT_DATE DATE,
    CATEGORY VARCHAR2(100 BYTE),
    CATEGORY_TYPE VARCHAR2(100 BYTE),
    CJSVERDICT_CODE VARCHAR2(100 BYTE),
    VERDICT_CODE VARCHAR2(100 BYTE),
    CREATED_ON TIMESTAMP (6) NOT NULL,
    CREATED_BY VARCHAR2(50)
)
    LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;