DROP TABLE MLA.XXMLA_QUEUE_MESSAGE_LOG CASCADE CONSTRAINTS;

CREATE TABLE MLA.XXMLA_QUEUE_MESSAGE_LOG
   (
    TRANSACTION_UUID VARCHAR2(200 BYTE) NOT NULL,
	MAAT_ID NUMBER NOT NULL,
	TYPE VARCHAR2(100 BYTE),
	MESSAGE BLOB,
	CREATED_TIME TIMESTAMP (6) NOT NULL
   )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE "MLA"."XXMLA_QUEUE_MESSAGE_LOG" ADD LAA_TRANSACTION_ID VARCHAR2(100 BYTE);