DROP TABLE MLA.XXMLA_HEARING CASCADE CONSTRAINTS;
CREATE TABLE MLA.XXMLA_HEARING
(
   HEARING_UUID VARCHAR2(100)  NOT NULL,
   MAAT_ID NUMBER,
   WQ_JURISDICTION_TYPE VARCHAR2(100),
   OU_COURT_LOCATION VARCHAR2(250),
   CREATED_DATE_TIME TIMESTAMP (6) NOT NULL,
   UPDATED_DATE_TIME TIMESTAMP (6)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;