DROP TABLE MLA.XXMLA_PLEA CASCADE CONSTRAINTS;
CREATE TABLE MLA.XXMLA_PLEA
(
    TX_ID NUMBER NULL,
    PLEA_VALUE VARCHAR2(100),
    PLEA_DATE DATE,
    OFFENCE_ID VARCHAR2(50),
    CASE_ID NUMBER,
    MAAT_ID NUMBER,
    CREATED_ON TIMESTAMP
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE MLA.XXMLA_PLEA ADD CONSTRAINT PK_PLEA_TX_ID PRIMARY KEY (TX_ID);



DROP TABLE MLA.XXMLA_VERDICT CASCADE CONSTRAINTS;
CREATE TABLE MLA.XXMLA_VERDICT
(
    TX_ID NUMBER NULL,
    OFFENCE_ID VARCHAR2(50),
    VERDICT_DATE DATE,
    CATEGORY VARCHAR2(100),
    CATEGORY_TYPE VARCHAR2(100),
    CJS_VERDICT_CODE VARCHAR2(100),
    VERDICT_CODE VARCHAR2(100),
    CASE_ID NUMBER,
    MAAT_ID NUMBER,
    CREATED_ON TIMESTAMP
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE MLA.XXMLA_VERDICT ADD CONSTRAINT PK_VERD_TX_ID PRIMARY KEY (TX_ID);


ALTER TABLE "MLA"."XXMLA_WQ_LINK_REGISTER" ADD PROSECUTION_CONCLUDED VARCHAR2(6);

