-- todo: Adding PK and FK constraint with Offence_id from Offence table?

DROP TABLE MLA.XXMLA_PLEA CASCADE CONSTRAINTS;

CREATE TABLE MLA.XXMLA_PLEA
(
    TX_ID NUMBER NOT NULL,
    PLEA_VALUE VARCHAR2(100),
    PLEA_DATE DATE,
    OFFENCE_ID VARCHAR2(50),
    CASE_ID NUMBER,
    MAAT_ID NUMBER,
    CREATED_ON TIMESTAMP
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE MLA.XXMLA_VERDICT CASCADE CONSTRAINTS;

CREATE TABLE MLA.XXMLA_VERDICT
(
    TX_ID NUMBER NOT NULL,
    OFFENCE_ID VARCHAR2(50),
    VERDICT_DATE DATE,
    CATEGORY VARCHAR2(100),
    CATEGORY_TYPE VARCHAR2(100),
    CJS_VERDICT_CODE VARCHAR2(100),
    VERDICT_CODE VARCHAR2(100),
    CASE_ID NUMBER,
    MAAT_ID NUMBER,
    CREATED_ON TIMESTAMP
)
    LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE "MLA"."XXMLA_WQ_CASE" ADD PROSECUTION_CONCLUDED VARCHAR2(6);
