REVOKE EXECUTE ON TOGDATA.ref_data_management FROM MLA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TOGDATA.CONTRIBUTION_FILE_ERRORS FROM MLA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TOGDATA.CONCOR_CONTRIBUTIONS FROM MLA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TOGDATA.FDC_CONTRIBUTIONS FROM MLA;
REVOKE SELECT ON TOGDATA.FDC_ITEMS FROM MLA;