GRANT EXECUTE ON TOGDATA.ref_data_management TO MLA;

GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.CONTRIBUTION_FILE_ERRORS TO MLA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.CONCOR_CONTRIBUTIONS TO MLA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.FDC_CONTRIBUTIONS TO MLA;
GRANT SELECT ON TOGDATA.FDC_ITEMS TO MLA;