ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify FORENAME varchar2(100);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify SURNAME varchar2(100);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE3 varchar2(100);
ALTER TABLE "MLA"."XXMLA_WQ_RESULT" modify RESULT_TEXT varchar2(4000);
ALTER TABLE "MLA"."XXMLA_WQ_OFFENCE" modify OFFENCE_WORDING varchar2(4000);

ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE1 varchar2(100);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE2 varchar2(100);
ALTER TABLE "MLA"."XXMLA_OFFENCE" modify OFFENCE_WORDING varchar2(4000);
COMMIT;

-- Following script is to reverse/back-out changes in case of any problem

ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify FORENAME varchar2(35);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify SURNAME varchar2(35);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE3 varchar2(35);
ALTER TABLE "MLA"."XXMLA_WQ_RESULT" modify RESULT_TEXT varchar2(2500);
ALTER TABLE "MLA"."XXMLA_WQ_OFFENCE" modify OFFENCE_WORDING varchar2(2500);

ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE1 varchar2(35);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE2 varchar2(35);
ALTER TABLE "MLA"."XXMLA_OFFENCE" modify OFFENCE_WORDING varchar2(2500);