ALTER TABLE "MLA"."XXMLA_DEFENDANT" modify NINO varchar2(15);
ALTER TABLE "MLA"."XXMLA_DEFENDANT" modify ADDRESS_LINE1 varchar2(50);
ALTER TABLE "MLA"."XXMLA_DEFENDANT" modify ADDRESS_LINE2 varchar2(50);
ALTER TABLE "MLA"."XXMLA_DEFENDANT" modify TELEPHONE_WORK varchar2(25);

ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify NINO varchar2(15);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE1 varchar2(50);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE2 varchar2(50);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify TELEPHONE_WORK varchar2(25);

COMMIT;


-- Following script is to reverse/back-out changes in case of any problem

ALTER TABLE "MLA"."XXMLA_DEFENDANT" modify NINO varchar2(9);
ALTER TABLE "MLA"."XXMLA_DEFENDANT" modify ADDRESS_LINE1 varchar2(35);
ALTER TABLE "MLA"."XXMLA_DEFENDANT" modify ADDRESS_LINE2 varchar2(35);
ALTER TABLE "MLA"."XXMLA_DEFENDANT" modify TELEPHONE_WORK varchar2(20);

ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify NINO varchar2(9);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE1 varchar2(35);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify ADDRESS_LINE2 varchar2(35);
ALTER TABLE "MLA"."XXMLA_WQ_DEFENDANT" modify TELEPHONE_WORK varchar2(20);

COMMIT;

-- Updating the data type - for defendant table

ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE NINO VARCHAR2(15) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE ADDRESS_LINE1 VARCHAR2(50) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE ADDRESS_LINE2 VARCHAR2(50) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE TELEPHONE_WORK VARCHAR2(25) CASCADE

