--MLA_LIBRA_DEFENDANT_REC
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE FORENAME VARCHAR2(100) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE SURNAME VARCHAR2(100) CASCADE

ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE ADDRESS_LINE1 VARCHAR2(100) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE ADDRESS_LINE2 VARCHAR2(100) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE ADDRESS_LINE3 VARCHAR2(100) CASCADE

COMMIT;

--MLA_LIBRA_OFFENCE_REC
ALTER TYPE MLA_LIBRA_OFFENCE_REC MODIFY ATTRIBUTE OFFENCE_WORDING VARCHAR2(4000) CASCADE
ALTER TYPE MLA_LIBRA_OFFENCE_REC MODIFY ATTRIBUTE OFFENCE_SHORT_TITLE VARCHAR2(300) CASCADE

COMMIT;

--MLA_LIBRA_RESULT_REC
ALTER TYPE MLA_LIBRA_RESULT_REC MODIFY ATTRIBUTE RESULT_SHORT_TITLE VARCHAR2(450) CASCADE
ALTER TYPE MLA_LIBRA_RESULT_REC MODIFY ATTRIBUTE RESULT_TEXT VARCHAR2(4000) CASCADE

COMMIT;