-- Rollback script
--MLA_LIBRA_DEFENDANT_REC
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE FORENAME VARCHAR2(35) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE SURNAME VARCHAR2(35) CASCADE

ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE ADDRESS_LINE1 VARCHAR2(35) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE ADDRESS_LINE2 VARCHAR2(35) CASCADE
ALTER TYPE MLA_LIBRA_DEFENDANT_REC MODIFY ATTRIBUTE ADDRESS_LINE3 VARCHAR2(35) CASCADE

COMMIT;

--MLA_LIBRA_OFFENCE_REC
ALTER TYPE MLA_LIBRA_OFFENCE_REC MODIFY ATTRIBUTE OFFENCE_WORDING VARCHAR2(2500) CASCADE
ALTER TYPE MLA_LIBRA_OFFENCE_REC MODIFY ATTRIBUTE OFFENCE_SHORT_TITLE VARCHAR2(120) CASCADE

COMMIT;

--MLA_LIBRA_RESULT_REC
ALTER TYPE MLA_LIBRA_RESULT_REC MODIFY ATTRIBUTE RESULT_SHORT_TITLE VARCHAR2(300) CASCADE
ALTER TYPE MLA_LIBRA_RESULT_REC MODIFY ATTRIBUTE RESULT_TEXT VARCHAR2(2500 BYTE) CASCADE

COMMIT;