REVOKE SELECT, INSERT, UPDATE, DELETE ON TOGDATA.EFORMS_AUDIT FROM MLA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TOGDATA.EFORMS_DECISION_HISTORY FROM MLA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TOGDATA.EFORMS_HISTORY FROM MLA;
REVOKE SELECT, INSERT, UPDATE, DELETE ON TOGDATA.EFORMS_RESULTS FROM MLA;