DROP TABLE MLA.XXMLA_DLRM_STATUS_UPDATE CASCADE CONSTRAINTS;
CREATE TABLE MLA.XXMLA_DLRM_STATUS_UPDATE
(
    ID NUMBER NULL,
    MAAT_ID NUMBER,
    OFFENCE_ID VARCHAR2(100),
    OFFENCE_CODE VARCHAR2(100),
    ERROR_MESSAGE VARCHAR2(4000),
    DATE_CREATED TIMESTAMP
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

GRANT SELECT, INSERT, UPDATE, DELETE ON MLA.XXMLA_DLRM_STATUS_UPDATE TO MLA;


CREATE SEQUENCE  "MLA"."DLRM_STATUS_UPDATE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1100 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
