GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.EFORMS_AUDIT TO MLA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.EFORMS_DECISION_HISTORY TO MLA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.EFORMS_HISTORY TO MLA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.EFORMS_RESULTS TO MLA;