ALTER TYPE TOGDATA.PASSPORT_ASSESSMENTTYPE DROP ATTRIBUTE UNDER_18 CASCADE;

ALTER TABLE TOGDATA.PASSPORT_ASSESSMENTS DROP CONSTRAINT PASS_UND18_CK;

ALTER TABLE TOGDATA.PASSPORT_ASSESSMENTS DROP COLUMN UNDER_18;