ALTER TABLE PASSPORT_ASSESSMENTS ADD UNDER_18 VARCHAR2(1);

ALTER TABLE TOGDATA.PASSPORT_ASSESSMENTS ADD (
    CONSTRAINT PASS_UND18_CK
    CHECK (UNDER_18 IN ('Y', 'N'))
);

ALTER TYPE PASSPORT_ASSESSMENTTYPE
    ADD ATTRIBUTE
    (
    UNDER_18 VARCHAR2(1)
    )
CASCADE;