GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.FIN_ASS_INCOME_EVIDENCE TO MLA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.INCOME_EVIDENCE TO MLA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TOGDATA.APPLICANT TO MLA;