begin

INSERT INTO "TOGDATA"."USER_ROLES" (USER_NAME, ROLE_NAME, USER_CREATED, DATE_CREATED, USER_ROLE_ENABLED) VALUES ('MLA', 'CCMT SUPERVISOR', 'MLA', TO_DATE('2020-04-23 18:45:44', 'YYYY-MM-DD HH24:MI:SS'), 'Y');
INSERT INTO "TOGDATA"."USER_ROLES" (USER_NAME, ROLE_NAME, USER_CREATED, DATE_CREATED, USER_ROLE_ENABLED) VALUES ('MLA', 'NCT SUPERVISOR', 'MLA', TO_DATE('2020-04-23 15:19:45', 'YYYY-MM-DD HH24:MI:SS'), 'Y');

end;


