package gov.uk.courtdata.enums;

public enum MessageType {
    LINK,
    UNLINK,
    LAA_STATUS,
    HEARING,
    PROSECUTION_CONCLUDED,
    LAA_STATUS_JOB,
    CREATE_LINK_CP_STATUS_JOB,
    LAA_STATUS_UPDATE,
    LAA_STATUS_REST_CALL,
    MEANS_ASSESSMENT_POST_PROCESSING
}
